# Generated by Django 6.0.2 on 2026-02-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_normalize_email_add_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano')], default='en', max_length=10),
        ),
    ]
