# Generated by Django 6.0.6 on 2026-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_publicdatasetemaildelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('fr', 'Français')], default='en', max_length=10),
        ),
    ]
