# Generated by Django 6.0.2 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="photo_thumbnail",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to="libraries/photos/thumbnails/%Y/%m/",
            ),
        ),
    ]
