# Generated by Django 6.0.2 on 2026-02-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_libraryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='libraries/photos/%Y/%m/'),
        ),
    ]
