# Generated by Django 6.0.2 on 2026-02-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_library_photo_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='is_indoor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='is_lit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='library',
            name='wheelchair_accessible',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('limited', 'Limited')], default='', max_length=10),
        ),
    ]
