# Generated by Django 6.0.2 on 2026-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_library_brand_library_capacity_library_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
