# Generated by Django 6.0.2 on 2026-02-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_add_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('mastodon_url', models.URLField(blank=True, default='')),
                ('bluesky_url', models.URLField(blank=True, default='')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='libraries.library')),
            ],
            options={
                'db_table': 'social_posts',
                'ordering': ['-posted_at'],
            },
        ),
    ]
