# Generated by Django 6.0.2 on 2026-02-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_socialpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instagram_tokens',
            },
        ),
        migrations.AddField(
            model_name='socialpost',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
