# Generated by Django 6.0.2 on 2026-03-01 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_add_instagram_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['city', 'address'], name='idx_lib_city_address'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['country'], name='idx_lib_country'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['status'], name='idx_lib_status'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['-created_at'], name='idx_lib_created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['city'], name='idx_lib_city'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['source'], name='idx_lib_source'),
        ),
    ]
