# Generated by Django 6.0.2 on 2026-03-01 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_library_idx_lib_city_address_library_idx_lib_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['status', '-created_at'], name='idx_lib_status_created'),
        ),
    ]
