# Generated by Django 6.0.2 on 2026-03-01 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_library_idx_lib_status_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='library',
            name='idx_lib_status',
        ),
        migrations.RemoveIndex(
            model_name='library',
            name='idx_lib_city',
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_lib_creator_created'),
        ),
        migrations.AddIndex(
            model_name='libraryphoto',
            index=models.Index(fields=['library', 'status'], name='idx_photo_library_status'),
        ),
        migrations.AddIndex(
            model_name='libraryphoto',
            index=models.Index(fields=['status', '-created_at'], name='idx_photo_status_created'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='idx_report_status_created'),
        ),
    ]
