# Generated by Django 6.0.2 on 2026-03-01 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0011_remove_library_idx_lib_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['operator'], name='idx_lib_operator'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['brand'], name='idx_lib_brand'),
        ),
    ]
