# Generated by Django 6.0.2 on 2026-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0013_alter_library_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
