# Generated by Django 6.0.2 on 2026-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_alter_library_rejection_reason_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
