# Generated by Django 6.0.2 on 2026-06-20 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0016_alter_library_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="libraryphoto",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="idx_photo_creator_created",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="idx_report_creator_created",
            ),
        ),
    ]
