# Generated by Django 6.0.6 on 2026-10-08 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0020_openstreetmap_contribution_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='photo_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_library_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='photo_origin',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('external', 'External'), ('unknown', 'Unknown')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='library',
            name='photo_source_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
