"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(*, name: str, default: bool) -> bool:
    """Parse an environment variable as a boolean setting.
    Supports common true and false string representations."""
    raw_value = os.environ.get(name)
    if raw_value is None:
        return default
    return raw_value.lower() in ("true", "1", "yes", "on")


def _env_int(*, name: str, default: int) -> int:
    """Parse an environment variable as an integer setting.
    Falls back to a safe default when parsing fails."""
    raw_value = os.environ.get(name)
    if raw_value is None:
        return default

    try:
        return int(raw_value)
    except ValueError:
        return default


DEBUG = _env_bool(name="DJANGO_DEBUG", default=True)
IS_TEST_ENVIRONMENT = any("pytest" in arg for arg in sys.argv) or "PYTEST_CURRENT_TEST" in os.environ

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-^^2(jhlow=omlc$eqcndv&qz3*-r3!l^=9y7-^-q4ly^@o0hg(" if DEBUG else "",
)
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set.")
if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be a secure production value.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1],testserver").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

SECURE_SSL_REDIRECT = _env_bool(
    name="DJANGO_SECURE_SSL_REDIRECT",
    default=not DEBUG and not IS_TEST_ENVIRONMENT,
)
SESSION_COOKIE_SECURE = _env_bool(
    name="DJANGO_SESSION_COOKIE_SECURE",
    default=not DEBUG and not IS_TEST_ENVIRONMENT,
)
CSRF_COOKIE_SECURE = _env_bool(
    name="DJANGO_CSRF_COOKIE_SECURE",
    default=not DEBUG and not IS_TEST_ENVIRONMENT,
)
SECURE_HSTS_SECONDS = _env_int(
    name="DJANGO_SECURE_HSTS_SECONDS",
    default=31536000 if not DEBUG and not IS_TEST_ENVIRONMENT else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
    name="DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=not DEBUG and not IS_TEST_ENVIRONMENT,
)
SECURE_HSTS_PRELOAD = _env_bool(
    name="DJANGO_SECURE_HSTS_PRELOAD",
    default=not DEBUG and not IS_TEST_ENVIRONMENT,
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

AUTH_RATE_LIMIT_ENABLED = _env_bool(name="AUTH_RATE_LIMIT_ENABLED", default=not DEBUG)
AUTH_RATE_LIMIT_WINDOW_SECONDS = _env_int(name="AUTH_RATE_LIMIT_WINDOW_SECONDS", default=300)
AUTH_RATE_LIMIT_LOGIN_ATTEMPTS = _env_int(name="AUTH_RATE_LIMIT_LOGIN_ATTEMPTS", default=10)
AUTH_RATE_LIMIT_REGISTER_ATTEMPTS = _env_int(name="AUTH_RATE_LIMIT_REGISTER_ATTEMPTS", default=5)
AUTH_RATE_LIMIT_REFRESH_ATTEMPTS = _env_int(name="AUTH_RATE_LIMIT_REFRESH_ATTEMPTS", default=15)

API_RATE_LIMIT_ENABLED = _env_bool(name="API_RATE_LIMIT_ENABLED", default=not DEBUG)
API_RATE_LIMIT_WINDOW_SECONDS = _env_int(name="API_RATE_LIMIT_WINDOW_SECONDS", default=300)
API_RATE_LIMIT_READ_REQUESTS = _env_int(name="API_RATE_LIMIT_READ_REQUESTS", default=60)
API_RATE_LIMIT_WRITE_REQUESTS = _env_int(name="API_RATE_LIMIT_WRITE_REQUESTS", default=10)

MAX_LIBRARY_PHOTO_UPLOAD_BYTES = _env_int(name="MAX_LIBRARY_PHOTO_UPLOAD_BYTES", default=8 * 1024 * 1024)
MAX_LIBRARY_PHOTO_SUBMISSION_BYTES = _env_int(name="MAX_LIBRARY_PHOTO_SUBMISSION_BYTES", default=8 * 1024 * 1024)
MAX_REPORT_PHOTO_UPLOAD_BYTES = _env_int(name="MAX_REPORT_PHOTO_UPLOAD_BYTES", default=5 * 1024 * 1024)


# Application definition

INSTALLED_APPS = [
    "config.apps.BookCornersAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.gis",
    "django.contrib.sitemaps",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_tasks_db",
    "users",
    "libraries",
]

TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate.ImmediateBackend"
        if IS_TEST_ENVIRONMENT
        else "django_tasks_db.DatabaseBackend",
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.google_oauth",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=600,
        engine="django.contrib.gis.db.backends.postgis",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG

# Auth

AUTH_USER_MODEL = "users.User"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# allauth account settings
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_ADAPTER = "users.adapters.AccountAdapter"
LOGIN_REDIRECT_URL = "/"

# allauth social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_ADAPTER = "users.adapters.SocialAccountAdapter"

_GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
_GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_ENABLED = bool(_GOOGLE_OAUTH_CLIENT_ID and _GOOGLE_OAUTH_CLIENT_SECRET)

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": _GOOGLE_OAUTH_CLIENT_ID,
                "secret": _GOOGLE_OAUTH_CLIENT_SECRET,
                "key": "",
            },
        ],
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    },
}

# Media files (uploads)

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# GIS libraries (macOS / Homebrew)

GDAL_LIBRARY_PATH = os.environ.get("GDAL_LIBRARY_PATH")
GEOS_LIBRARY_PATH = os.environ.get("GEOS_LIBRARY_PATH")


NOMINATIM_USER_AGENT = os.environ.get("NOMINATIM_USER_AGENT", "book-corners/1.0")
try:
    NOMINATIM_TIMEOUT_SECONDS = int(os.environ.get("NOMINATIM_TIMEOUT_SECONDS", "5"))
except ValueError:
    NOMINATIM_TIMEOUT_SECONDS = 5


# Sentry error tracking
# Enabled automatically when SENTRY_DSN is set. No-op otherwise.

# Email notifications (Resend)
ADMIN_NOTIFICATION_EMAIL = os.environ.get("ADMIN_NOTIFICATION_EMAIL", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Book Corners <noreply@bookcorners.org>")
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
if RESEND_API_KEY:
    INSTALLED_APPS += ["anymail"]  # noqa: F811
    ANYMAIL = {"RESEND_API_KEY": RESEND_API_KEY}
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Social media posting
MASTODON_INSTANCE_URL = os.environ.get("MASTODON_INSTANCE_URL", "")
MASTODON_ACCESS_TOKEN = os.environ.get("MASTODON_ACCESS_TOKEN", "")
BLUESKY_HANDLE = os.environ.get("BLUESKY_HANDLE", "")
BLUESKY_APP_PASSWORD = os.environ.get("BLUESKY_APP_PASSWORD", "")

SENTRY_DSN = os.environ.get("SENTRY_DSN", "")

if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        release=os.environ.get("GIT_REV", ""),
        environment="production" if not DEBUG else "development",
        traces_sample_rate=0.1,
        send_default_pii=False,
    )
